### ISSUE TITLE
Demo: Multiple Movable Objects

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#24]
### Story
@opentecture/the-brains 

### [Multiple Movable Objects]( https://opentecture.github.io/mindmapping/master/connect-edit/multiple-movable-objects/multiple-movable-objects.html )
![image](https://user-images.githubusercontent.com/547626/41770673-b883b302-75c7-11e8-9d09-b31a36e0d710.png)

Can we have multiple random movable objects using the Three.js TransformControls? And, if so, is the complexity of the workflow at a low enough level to be usable?

This example indicates a positive response

* Draws 50 Three.js primitives
* Each primitive display the transform controls upon mouseover
* Textual data attached to the object is accessible upon mouseover and displayed in the left menu
* A button causes one-off not-smart arrows to be drawn from the objects to a rarget

Notes

This is another sandbox experiment. Perhaps you could say it's parallel to previous efforts as opposed to a successor.

The code is MUCH simpler with straight lines instead of polylines. For now we should proably sticck to straight lines and add the polylines in once things start to settle down

@afomi 

Am I correct in thinking that you prefer the arrow-driven movement - as used here - over the free form movement of objects in [MindMap 3D R5.2]( https://opentecture.github.io/mindmapping/master/mindmap-3d/r5/mindmap3d.html )?

**Comment by afomi** [comment]
@theo-armour 

Being able to move each `node` in 3d space makes sense.

A good implemetation UX-wise will be key.
I think we can consider adding this feature in as simply as possible - free transform tools on the selection of a node. More interactions will be added as we go.

I'm not sure I follow you on the arrow driven movement issue.  I did have thoughts about the UI control difficulty of moving 3d items in space and thought about limiting movement to a 2d plane - that would have to be toggled in 3 ways (x, y, z). Those details can live in another Issue.

Is the code for polylines in? Or just straight lines? If we have the complex code, we should consider keeping the style of line as an option. Otherwise, simple straight lines are good enough for now.

**Comment by afomi** [comment]
I've incorporated basic line drawing into the `/build`, in its `Demo Mode`

The niceties in the implementation, like `HideCancelTransform` are note in this build and can be addressed as separate Issues.

Here's the basic lines drawing, and the X, Y, Z coordinates.

I was also able to connect what I originally hoping for: discrete X, Y, Z editing - which is how `TransformControls` works out of the box 😄 

![boxes](https://user-images.githubusercontent.com/67984/41816828-aaec06c2-7743-11e8-88d1-4e65f11b6041.png)

**Comment by theo-armour** [comment]
@afomi 

Looks really good. More comments tomorrow.
